### ISSUE TITLE
Build does not produce System.Runtime.CompilerServices.Unsafe.dll

### ISSUE THREAD

**Issue by locbones** [eezstreet/D2RModding-StrEdit#2]
For a yet unknown reason or configuration type(both debug and release were attempted), the solution will fail to produce the above mentioned DLL upon build completion. Build log produced no errors during process.
Resulting in the following fatal error when attempting to open a workspace:
https://cdn.discordapp.com/attachments/846033631326765097/850784098279751680/Str_error.PNG

**Comment by eezstreet** [comment]
This has been fixed.
